spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/processManager}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:1383}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        types:
          print:
            banner: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  ai:
    openai:
      api-key: ${openaiAPI_KEY}
      model: gpt-4o-mini
      chat:
        options:
          model: gpt-4o-mini
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://ngcloak.onrender.com/realms/ProcessManagement}

        registration:
          keycloak:
            provider: keycloak
            client_id: ${KEYCLOAK_CLIENT_ID:processManager}
            client_secret: ${KEYCLOAK_CLIENT_SECRET:ttXmZIEHmwmO4E2NeSUCllD3NIEVpZUW}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      ProcessModelIdUnique: PROCESS_MODEL_ID_UNIQUE
      ProcessProcessNameUnique: PROCESS_PROCESS_NAME_UNIQUE
      ValidFileType: VALID_FILE_TYPE
server:
  tomcat:
    max-part-count: '100'
  port: 9000
springdoc:
  pathsToMatch: /api/**
keycloak:
  base-url: ${KEYCLOAK_BASE_URI:https://ngcloak.onrender.com}
  client-id: ${KEYCLOAK_CLIENT_ID:processManager}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:ttXmZIEHmwmO4E2NeSUCllD3NIEVpZUW}
app:
  processKey: "caseManager"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    tech.justjava.process_manager: DEBUG
    org.springframework.web: DEBUG