name: build-processmanager
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install glibc
        run: sudo apt-get update && sudo apt-get install -y libc6
      - name: Build jar
        run: mvn clean compile jib:build
#      - name: Deploy to test
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: srv-cvr6b2je5dus7387aij0
#          api-key: rnd_VmQJ50o6AWfdo2RB0vmrjOpur53F
#          wait-for-success: true

# https://api.render.com/deploy/srv-cvr6b2je5dus7387aij0?key=VciC2INsDjw
# https://api.render.com/deploy/srv-cvr6b2je5dus7387aij0?key=VciC2INsDjw
# https://api.render.com/deploy/srv-d28tmeer433s73bv9qbg?key=O_ecYtPkZc4